"""初始迁移：创建全部表

Revision ID: b87450087b48
Revises: 
Create Date: 2026-07-01 12:06:40.618258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87450087b48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='智能体名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='功能介绍'),
    sa.Column('agent_type', sa.String(length=20), nullable=False, comment='类型：annotator / chat'),
    sa.Column('config_json', sa.Text(), nullable=True, comment='JSON 格式，存储 top_k、温度等参数'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='配置名称'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='提供商：openai / qwen / deepseek'),
    sa.Column('model', sa.String(length=50), nullable=False, comment='模型名称，如 deepseek-chat'),
    sa.Column('api_key', sa.String(length=200), nullable=False, comment='API Key（生产环境应加密存储）'),
    sa.Column('base_url', sa.String(length=200), nullable=True, comment='自定义 API 端点'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='当前使用的配置'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录用户名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('password_hash', sa.String(length=128), nullable=False, comment='bcrypt 密码哈希'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色：admin / teacher'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='账号是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='注册时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False, comment='学科代码，如 DS、OS'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='学科名称，如 数据结构'),
    sa.Column('description', sa.Text(), nullable=True, comment='简介'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='调用用户'),
    sa.Column('agent_id', sa.Integer(), nullable=True, comment='关联智能体'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='动作：annotate / chat / index_doc'),
    sa.Column('input_summary', sa.Text(), nullable=True, comment='输入摘要（前 100 字）'),
    sa.Column('tokens_used', sa.Integer(), nullable=True, comment='消耗 token 数'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='耗时（毫秒）'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：success / error'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='调用时间'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False, comment='服务器存储路径'),
    sa.Column('original_name', sa.String(length=200), nullable=False, comment='原始文件名'),
    sa.Column('doc_type', sa.String(length=20), nullable=False, comment='类型：reference（参考资料）/ questions（题目文档）'),
    sa.Column('subject_id', sa.Integer(), nullable=False, comment='所属学科'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：pending / processing / done / failed'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='上传者'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='上传时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False, comment='所属学科'),
    sa.Column('code', sa.String(length=20), nullable=False, comment='自动生成编码，如 DS-KP-001'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='知识点名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='详细描述，也是嵌入的文本来源'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='软删除标记'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False, comment='所属学科'),
    sa.Column('content', sa.Text(), nullable=False, comment='题目正文'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='题型：choice / judgment / short_answer / programming'),
    sa.Column('difficulty', sa.Integer(), nullable=True, comment='难度 1–5，由 LLM 标注'),
    sa.Column('source_doc_id', sa.Integer(), nullable=True, comment='来源文档（批量导入时填写）'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_doc_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_kp_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='题目 ID'),
    sa.Column('kp_id', sa.Integer(), nullable=False, comment='知识点 ID'),
    sa.Column('confidence', sa.Integer(), nullable=True, comment='LLM 输出的置信度 0.0–1.0，实际存储为整数百分比'),
    sa.Column('is_manual', sa.Boolean(), nullable=True, comment='是否为教师手动修正'),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_points.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_kp_map')
    op.drop_table('questions')
    op.drop_table('knowledge_points')
    op.drop_table('documents')
    op.drop_table('system_logs')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('llm_configs')
    op.drop_table('agents')
    # ### end Alembic commands ###
